In [1]:
%load_ext autoreload
%autoreload 2
import sys, os
parent_dir = os.path.abspath(os.path.join(os.path.dirname("..."), "..."))
sys.path.append(parent_dir)
import pandas as pd

In [8]:
# read csv file
df = pd.read_csv('../dataset/Train.csv')
df

,responseId,view_label,ID_enter,ID_exit,videos,video_time,datetimestamp_start,datetimestamp_end,date,signaling,congestion_enter_rating,congestion_exit_rating,time_segment_id,cycle_phase
0,zYkHaeOdB7XOnvgP3YW5kQs,Norman Niles #1,time_segment_0_Norman Niles #1_congestion_ente...,time_segment_0_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-00-45.mp4,2025-10-20 06:00:45,2025-10-20 06:00:45,2025-10-20 06:01:44,2025-10-20,none,free flowing,free flowing,0,train
1,NYsHaeCRLq-vnvgPjoXZqA0,Norman Niles #1,time_segment_1_Norman Niles #1_congestion_ente...,time_segment_1_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-01-45.mp4,2025-10-20 06:01:45,2025-10-20 06:01:45,2025-10-20 06:02:44,2025-10-20,none,free flowing,free flowing,1,train
2,A40HaYT8KNm7nvgPq8e12AU,Norman Niles #1,time_segment_2_Norman Niles #1_congestion_ente...,time_segment_2_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-02-45.mp4,2025-10-20 06:02:45,2025-10-20 06:02:45,2025-10-20 06:03:00,2025-10-20,none,free flowing,free flowing,2,train
3,EIsHaanDMK-vnvgPjoXZqA0,Norman Niles #1,time_segment_3_Norman Niles #1_congestion_ente...,time_segment_3_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-03-45.mp4,2025-10-20 06:03:45,2025-10-20 06:03:45,2025-10-20 06:04:44,2025-10-20,none,free flowing,free flowing,3,train
4,RYsHafSeMaqpmecP5vCV0AQ,Norman Niles #1,time_segment_4_Norman Niles #1_congestion_ente...,time_segment_4_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-04-45.mp4,2025-10-20 06:04:45,2025-10-20 06:04:45,2025-10-20 06:04:59,2025-10-20,none,free flowing,free flowing,4,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16071,0YkHacyJMq-vnvgPjoXZqA0,Norman Niles #4,time_segment_4982_Norman Niles #4_congestion_e...,time_segment_4982_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-55-45.mp4,2025-10-26 17:55:45,2025-10-26 17:55:40,2025-10-26 17:56:40,2025-10-26,low,moderate delay,free flowing,4982,train
16072,PYoHaan6Lb-envgP6uGTmAE,Norman Niles #4,time_segment_4983_Norman Niles #4_congestion_e...,time_segment_4983_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-56-45.mp4,2025-10-26 17:56:45,2025-10-26 17:56:41,2025-10-26 17:57:59,2025-10-26,high,moderate delay,free flowing,4983,train
16073,7ooHafDLFdP_ld8Piv3HsQo,Norman Niles #4,time_segment_4984_Norman Niles #4_congestion_e...,time_segment_4984_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-57-45.mp4,2025-10-26 17:57:45,2025-10-26 17:57:42,2025-10-26 17:58:00,2025-10-26,medium,light delay,free flowing,4984,train
16074,0okHabnnG-K2nvgPsZGZ4Aw,Norman Niles #4,time_segment_4985_Norman Niles #4_congestion_e...,time_segment_4985_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-58-45.mp4,2025-10-26 17:58:45,2025-10-26 17:58:42,2025-10-26 17:59:57,2025-10-26,none,light delay,free flowing,4985,train
16075,aYwHae2SDrXOnvgP3YW5kQs,Norman Niles #4,time_segment_4986_Norman Niles #4_congestion_e...,time_segment_4986_Norman Niles #4_congestion_e...,normanniles4/normanniles4_2025-10-26-17-59-45.mp4,2025-10-26 17:59:45,2025-10-26 17:59:39,2025-10-26 18:00:59,2025-10-26,none,free flowing,free flowing,4986,train

In [3]:
# read csv file
df_consolidated = pd.read_csv('../consolidated_results.csv')
df_consolidated.T

,0,1,2,3
filename,normanniles1_2025-10-20-08-59-45.annotated,normanniles1_2025-10-20-08-59-45,normanniles1_2025-10-20-09-00-45.annotated,normanniles1_2025-10-20-09-00-45
camera,normanniles1,normanniles1,normanniles1,normanniles1
date,2025-10-20,2025-10-20,2025-10-20,2025-10-20
time,08:59:45,08:59:45,09:00:45,09:00:45
datetime,2025-10-20 08:59:45,2025-10-20 08:59:45,2025-10-20 09:00:45,2025-10-20 09:00:45
...,...,...,...,...
poly_unique_vehicles_north_exit,1,6,0,8
poly_vtype_car_north_circulating,2,5,5,11
poly_vtype_car_north_entry,NaN,2.0,NaN,NaN
poly_vtype_car_north_exit,1.0,6.0,NaN,8.0
poly_vtype_truck_north_circulating,1.0,1.0,NaN,NaN

In [21]:
# Load from the video_processed_files directory the jsons and load them as a dataframe
import json
import pandas as pd
import os
data_dir = '../video_processed_files'
all_data = []
for subdir in os.listdir(data_dir):
    subdir_path = os.path.join(data_dir, subdir)
    if os.path.isdir(subdir_path):
        for filename in os.listdir(subdir_path):
            if filename.endswith('.json'):
                with open(os.path.join(subdir_path, filename), 'r') as f:
                    data = json.load(f)
                    # save a column 'videos' which is the folder name/
                    data['videos'] = f"{subdir}/{filename.replace('.json','.mp4')}"
                    all_data.append(data)
segmented_video_df = pd.DataFrame(all_data)

In [22]:
segmented_video_df.loc[0]['videos']

'normanniles1/normanniles1_2025-10-20-09-00-45.mp4'

In [23]:
# merge the two dataframes on videos column
merged_df = pd.merge(df, segmented_video_df, on='videos', how='inner')
merged_df

,responseId,view_label,ID_enter,ID_exit,videos,video_time,datetimestamp_start,datetimestamp_end,date_x,signaling,...,poly_size_std_north_queue,poly_conf_mean_north_queue,poly_conf_median_north_queue,poly_vtype_bus_north_circulating,poly_vtype_truck_north_circulating,poly_vtype_bus_north_entry,poly_vtype_truck_north_exit,poly_vtype_bus_north_exit,poly_vtype_bus_north_queue,poly_vtype_truck_north_queue
0,04kHaYDsKJ__698PweWaiQ4,Norman Niles #1,time_segment_179_Norman Niles #1_congestion_en...,time_segment_179_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-08-59-45.mp4,2025-10-20 08:59:45,2025-10-20 08:59:45,2025-10-20 09:00:44,2025-10-20,none,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,AIsHaZeCH7zA698P_KuO8AM,Norman Niles #1,time_segment_180_Norman Niles #1_congestion_en...,time_segment_180_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-09-00-45.mp4,2025-10-20 09:00:45,2025-10-20 09:00:45,2025-10-20 09:01:00,2025-10-20,none,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,_4wHadfNC7Ov3NoPq7G46QE,Norman Niles #1,time_segment_342_Norman Niles #1_congestion_en...,time_segment_342_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-11-44-45.mp4,2025-10-20 11:44:45,2025-10-20 11:44:44,2025-10-20 11:45:44,2025-10-20,medium,...,164.319143,0.452681,0.439131,NaN,24.0,NaN,NaN,NaN,NaN,2.0
3,I40HacHGKKHXnvgP76fxyQI,Norman Niles #1,time_segment_343_Norman Niles #1_congestion_en...,time_segment_343_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-11-45-45.mp4,2025-10-20 11:45:45,2025-10-20 11:45:44,2025-10-20 11:46:44,2025-10-20,low,...,254.837099,0.473855,0.464973,NaN,21.0,NaN,2.0,NaN,NaN,NaN
4,WIoHaai-DrHZnvgPgt-ZqQs,Norman Niles #1,time_segment_516_Norman Niles #1_congestion_en...,time_segment_516_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-14-40-45.mp4,2025-10-20 14:40:45,2025-10-20 14:40:44,2025-10-20 14:41:43,2025-10-20,medium,...,135.659306,0.503666,0.500100,NaN,7.0,NaN,NaN,NaN,NaN,4.0
5,8IwHabO1MOaQ2PgPqvKU8As,Norman Niles #1,time_segment_517_Norman Niles #1_congestion_en...,time_segment_517_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-14-41-45.mp4,2025-10-20 14:41:45,2025-10-20 14:41:44,2025-10-20 14:42:44,2025-10-20,low,...,212.004298,0.477869,0.462823,14.0,25.0,6.0,8.0,2.0,3.0,1.0
6,7YoHabyDMZKdmecPt_3RiQ4,Norman Niles #1,time_segment_812_Norman Niles #1_congestion_en...,time_segment_812_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-21-07-39-45.mp4,2025-10-21 07:39:45,2025-10-21 07:39:45,2025-10-21 07:40:44,2025-10-21,none,...,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,NaN
7,AYoHaebpMfK1ld8PufLf6AI,Norman Niles #1,time_segment_813_Norman Niles #1_congestion_en...,time_segment_813_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-21-07-40-45.mp4,2025-10-21 07:40:45,2025-10-21 07:40:45,2025-10-21 07:41:44,2025-10-21,none,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,KYsHaYfkEJSgmecP8YHv4Qc,Norman Niles #1,time_segment_969_Norman Niles #1_congestion_en...,time_segment_969_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-21-10-16-45.mp4,2025-10-21 10:16:45,2025-10-21 10:16:45,2025-10-21 10:17:44,2025-10-21,none,...,209.790438,0.515784,0.507081,3.0,13.0,1.0,1.0,NaN,1.0,1.0
9,8owHafO_DsjtnvgP8NiHuAw,Norman Niles #1,time_segment_970_Norman Niles #1_congestion_en...,time_segment_970_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-21-10-17-45.mp4,2025-10-21 10:17:45,2025-10-21 10:17:45,2025-10-21 10:18:45,2025-10-21,none,...,251.604865,0.477878,0.471123,4.0,9.0,NaN,NaN,NaN,NaN,NaN